### ISSUE TITLE
Defense Feedback

### ISSUE THREAD

**Issue by MichaelDurlingGeneralElectric** [ge-high-assurance/VERDICT#80]
There is a need to clarify the NIST 800-53 calculation and feedback.

The Cyber Defense Properties may be set as integers from 0 to 9. Currently the recommended practice is to use 0 for no defense, 3 for a defense to a minor consequence threat, 5 for a defense to a major consequence threat, 7 for a defense to a hazardous consequence threat and 9 for a defense to a catastrophic consequence threat. The NIST 800-53 standard calls out low, medium and high defense levels.

There is a need to align the NIST low, moderate and high defense control levels with the consequence of threat levels and the cyber defense metrics.

One option is to limit cyber defense property values to 0, 3, 5, 7, 9, then align NIST as 0 - none, 3 - low, 5 - moderate, and 7 and 9 to high.

**Comment by baoluomeng** [comment]
I don't think we need to we need to align with NIST control at the front-level and first level of feedback as (1) it would contradict the original design purpose and (2) we need to re-think almost everything of MBAA. The only place we introduce NIST control is at the fine-grain (second-level) view of recommended defenses and DAL for failed requirements. 

According to the DASC VERDICT paper, currently, encoding the defense property as a numeric value in the front-end represents the design assurance level (A, B, C, D, E). And the the "Acceptable Likelihood of Successful Attack" in the MBAA feedback is directly from the "Severity" field of cyber requirements, and the conversion from the enumerated value of severity to a numeric value was originally guided by DO-356A. So 


However, I think we need a 5-value enumerated type e.g., [None, Low, Moderate, High, Critical] to represent the rigor of defense property (DAL) (5-values) and also the severity level (5-values) so that we can use the terminology consistently from front-end to back-end.

**Comment by MichaelDurlingGeneralElectric** [comment]
Actions:

For Likelihood of Successful Attack

- Change the column heading title from Acceptable Likelihood of Successful Attack to Severity of Successful Attack 
- Display  Catastrophic instead of 1 e-9, Hazardous instead of 1 e-7, Major instead of 1 e-5, Minor instead of 1 e -3 and 1 to none

For Calculated Likelihood of Successful Attack

- Change the column heading title from Calculated Likelihood of Successful Attack to Implemented Security Design Assurance Level
- Display A if <= 1e-9, B if <= 1 e-7 && > 1 e-9, C if <= 1 e-5 && > 1e-7, D if <= 1 e-3 && > 1e-5, else E

**Comment by MichaelDurlingGeneralElectric** [comment]
This change impacts MBA primary, synthesis and assurance case GUI

**Comment by MichaelDurlingGeneralElectric** [comment]
Implemented and checked out in release 1.5.0
